### ISSUE TITLE
Inferring what to inject

### ISSUE THREAD

**Issue by colin-jack** [cesarenaldi/iniettore#1]
Great looking project but I was wondering if you've thought about implicitly injecting:

``` js
class UltimateQuestion {
    constructor(@answer) {
        console.log(@answer)
    }
}

var rootContext = iniettore.create(function (map) {
    map('answer').to(42).as(VALUE)
    map('question').to(UltimateQuestion).as(LAZY, SINGLETON, CONSTRUCTOR) //.injecting('answer')
})
```

To me that's one of the big benefits of IoC frameworks, they take care of this plumbing. Doing it by argument naming (@answer) rather than based on say implementing an interface maybe isn't perfect but it'd still be useful I think.

**Comment by cesarenaldi** [comment]
Thanks, I'm happy you like my work.

I find inferring dependencies from the constructor/function signature a very elegant option. The main reason I didn't implement it is because function argument names gets lost when the library gets minified (for example in a client build).

It's also the main reason why AngularJS DI container offers other [annotation strategies](https://docs.angularjs.org/guide/di) to infer the dependencies.

Said that two possible options are:
- inferring dependencies at build-time providing a transpiling tool to integrate in the project build pipeline (e.g. browserify plugin, jstransform visitor). The tool should decorate the constructor/function with a property (e.g. $inject a la AngularJS style) that can be used at run-time to auto-wire the context objects.
- enabling such functionality when the library run on Node.js where minification is "usually" not required.

On top of my head I cannot think at any other solutions. I'm quite open to any suggestion.

**Comment by colin-jack** [comment]
Ahh sorry hadn't realized you were targeting browser too. 

On your options, having a build process might be nice but it does increase the hassle in terms of using the framework and its also something you could add later. Given that I'd think you're option of allowing implicit annotation but with the caveat you should only use it when minification is not being performed (e.g. server-side) would be enough.

I guess another good option would be to implement implicit annotation now then if people wanted it you could later add the other Angular approaches, the advantage of using their approaches being that if Angular does win out there will be a lot of developers with experience of the DI aspects of it.

**Comment by cesarenaldi** [comment]
You definitely raised valid points.

In terms of API design, I'm evaluating two options. What's your opinion?

## Explicit API

This can give the developer freedom to chose to use the implicit annotation per binding.

```
class UltimateQuestion {
    constructor(answer) {
        console.log(answer)
    }
}

var rootContext = iniettore.create(function (map) {
    map('answer').to(42).as(VALUE)
    map('question').to(UltimateQuestion).as(LAZY, SINGLETON, CONSTRUCTOR).autoWire()
})
```

## Fully implicit approach

As you suggested using some sort of naming convention to figure out the dependency names.

```
class UltimateQuestion {
    constructor($answer) {
        console.log($answer)
    }
}
```

Unfortunately cannot use the `@` symbol.

**Comment by colin-jack** [comment]
Sorry yeah I shouldn't have included @ in original, of the options $ and _ I'd go for $. 

As to whether $answer or answer with autowire is clearer, to me its much of a muchness. I guess I slightly prefer the $answer approach because it highlights the fact the dependency is injected to anyone looking at the code.

Either would be fine with me though :)

**Comment by cesarenaldi** [comment]
I started working on an implementation on this branch: https://github.com/cesarenaldi/iniettore/tree/implicit-annotation

See this test for the use case: https://github.com/cesarenaldi/iniettore/blob/implicit-annotation/test/spec/implicitAnnotation.spec.js

I still have to figure out a couple of use cases and write some documentation.

**Comment by colin-jack** [comment]
Excellent ta, I'll pull it down and give it a shot in the next week and let you know how I get on.

**Comment by cesarenaldi** [comment]
Merged into master branch. Full documentation will follow in the v2.0.0 release
